services:
  db:
    image: postgres
    restart: always
    volumes:
      - awesome-shop:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  awesome-shop:
